INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Beer','Brewery','Country','Region',0.00,null,0.00,'Style',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Foster''s Lager (Oil Can)','Foster’s Group','Australia','',4.00,null,27.00,'Pale Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Affligem Tripel','Affligem Brouwerij','Belgium','',9.00,null,25.00,'Tripel ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Chimay Bleue (Blue)','Bières de Chimay ','Belgium','',9.00,null,11.00,'Belgian Strong Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Chimay Cinq Cents (White)','Bières de Chimay ','Belgium','',8.00,null,11.00,'Tripel ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Chimay Premiere (Red)','Bières de Chimay ','Belgium','',7.00,null,11.00,'Dubbel ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Hoegaarden White','Brouwerij van Hoegaarden','Belgium','',5.00,null,12.00,'Witbier ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Lambic Framboise (Raspberry)','Brouwerij Lindemans','Belgium','',2.50,null,12.00,'Lambic - Fruit ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Lambic Pêche (Peach)','Brouwerij Lindemans','Belgium','',2.50,null,12.00,'Lambic - Fruit ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Orval Trappist','Brasserie d''Orval','Belgium','',6.00,null,12.00,'Pale Ale - Belgian',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Stella Artois','Stella Artois','Belgium','',5.20,null,12.00,'Lager - Euro',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Xingu','Heineken Brasil','Brazil','',4.60,null,12.00,'Lager - Black',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Labatt Blue','Labatt Brewing Company','Canada','',5.00,null,12.00,'Lager - North American Adjunct',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Moosehead Lager','Moosehead Breweries Limited','Canada','',5.00,null,12.00,'Lager - North American Adjunct',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Tsingtao','Tsingtao Brewery','China','',4.70,null,12.00,'Lager - Pale',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Pilsner Urquell','Plzeňský Prazdroj','Czech Republic','',4.40,null,12.00,'Pilsner - Czech ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Boddington’s Pub Ale','Boddington’s Brewery','England','',5.00,null,12.00,'Brown Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Fuller''s London Pride','"Fuller','4.1','England',0.00,null,0.00,' Smith & Turner"',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Monty Python''s Holy Grail Ale','Black Sheep Brewery','England','',4.70,null,12.00,'English Pale Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Newcastle Brown Ale','Tadcaster Brewery','England','',4.70,null,12.00,'Brown Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Sam Smith Nut Brown','Samuel Smith''s Old Brewery','England','',5.00,null,12.00,'Brown Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Samuel Smith Oatmeal Stout','Samuel Smith''s Old Brewery','England','',5.00,null,16.00,'Sweet Stout ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Samuel Smith Pale Ale','Samuel Smith''s Old Brewery','England','',5.00,null,12.00,'American Pale Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Samuel Smith Pure Brewed Lager','Samuel Smith''s Old Brewery','England','',5.00,null,12.00,'Premium Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Samuel Smith Taddy Porter','Samuel Smith''s Old Brewery','England','',5.00,null,12.00,'Porter ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Samuel Smith''s Imperial Stout','Samuel Smith''s Old Brewery','England','',7.00,null,12.00,'Imperial Stout ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Samuel Smith''s Winter Welcome Ale','Samuel Smith''s Old Brewery','England','',6.00,null,12.00,'Winter Warmer ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Wells & Young''s Double Chocolate Stout','Charles Wells Brewery','England','',5.20,null,14.00,'Sweet Stout',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Becks','Brauerei Beck','Germany','',4.90,null,12.00,'Pilsner - German',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Bitburger','Bitburger Braugruppe','Germany','',4.80,null,12.00,'Pilsner ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Celebrator Doppelbock','Brauerei Aying','Germany','',6.70,null,12.00,'Doppelbock ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Erdinger Crystal Hefe','Erdinger Weissbräu','Germany','',5.30,null,12.00,'Hefeweizen',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Franziskaner Hefe-Weissbier','Spaten-Franziskaner-Löwenbräu-Gruppe','Germany','',5.00,null,16.00,'German Hefeweizen ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Konig Ludwig Weiss','König Ludwig Schlossbrauerei Kaltenberg','Germany','',5.50,null,12.00,'German Hefeweizen ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Köstritzer Schwarzbier','Köstritzer Schwarzbierbrauerei','Germany','',4.80,null,14.00,'Schwarzbier ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Leibinger Seeradler Clasik','Brauerei Max Leibinger','Germany','',2.80,null,12.00,'Radler',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Leibinger Zepplin','Brauerei Max Leibinger','Germany','',5.20,null,12.00,'Kellerbier / Zwickelbier',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Spaten Optimator','Spaten-Franziskaner-Löwenbräu-Gruppe','Germany','',7.60,null,14.00,'Doppelbock ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Spaten Premium Lager','Spaten-Franziskaner-Löwenbräu-Gruppe','Germany','',5.20,null,12.00,'Premium Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('St. Pauli Girl','Brauerei Beck','Germany','',4.90,null,12.00,'Premium Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Warsteiner Dunkel','Warsteiner','Germany','',4.80,null,12.00,'Lager - Dunkel Munich',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Warsteiner Premium ','Warsteiner','Germany','',4.80,null,12.00,'Pilsner - German',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Amstel Light','Amstel Bier','Holland','',3.50,null,12.00,'Pale Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Grolsch','Koninklijke Grolsch','Holland','',5.00,null,14.00,'Premium Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Heineken','Heineken','Holland','',5.00,null,12.00,'Lager - Euro',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Heineken Light','Heineken','Holland','',3.20,null,12.00,'Lager - Euro',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Taj Mahal','United Breweries (India)','India','',4.50,null,14.00,'Lager - Pale',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Guinness','Guiness','Ireland','',4.30,null,12.00,'Stout - Irish Dry',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Harp Lager','Guinness','Ireland','',5.00,null,12.00,'Lager - Euro',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Murphy’s Irish Stout','Heineken Brewery Ireland','Ireland','',4.00,null,12.00,'Stout - Irish Dry',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Moretti','Birra Moretti','Italy','',5.00,null,12.00,'Pale Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Moretti La Rossa','Birra Moretti','Italy','',7.20,null,12.00,'Doppelbock ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Peroni','Birra Peroni','Italy','',5.10,null,12.00,'Lager - Euro',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Red Stripe','Desnoes & Geddes','Jamaica','',4.70,null,12.00,'Lager - North American Adjunct',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Kirin','Kirin Brewery Company','Japan','',4.95,null,12.00,'Lager - Pale',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Sapporo Premium','Sapporo Breweries','Japan','',4.70,null,12.00,'Lager - Japanese Rice',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Carta Blanca','Cervecería Cuauhtémoc Moctezuma S.A. de C.V.','Mexico','',4.50,null,12.00,'Lager - North American Adjunct',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Corona Extra','Grupo Modelo S.A. de C.V.','Mexico','',4.60,null,12.00,'Lager - North American Adjunct',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Corona Light','Grupo Modelo S.A. de C.V.','Mexico','',4.00,null,12.00,'Lager - North American Light',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Dos Equis XX Amber','Cervecería Cuauhtémoc Moctezuma S.A. de C.V.','Mexico','',4.70,null,12.00,'Lager - Vienna / Amber',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Dos Equis XX Special Lager','Cervecería Cuauhtémoc Moctezuma S.A. de C.V.','Mexico','',4.45,null,12.00,'Lager - North American Adjunct',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Modelo Especial','Grupo Modelo S.A. de C.V.','Mexico','',4.50,null,12.00,'Lager - North American Light',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Negra Modelo','Grupo Modelo S.A. de C.V.','Mexico','',5.30,null,12.00,'Lager - Vienna / Amber',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Pacifico Clara','Grupo Modelo S.A. de C.V.','Mexico','',4.50,null,12.00,'Lager - North American Adjunct',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Tecate','Cervecería Cuauhtémoc Moctezuma S.A. de C.V.','Mexico','',4.50,null,12.00,'Lager - North American Adjunct',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Belhaven Scottish Ale','Belhaven Brewery','Scotland','',5.20,null,12.00,'Scottish Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Estrella Damm','Grupo Damm','Spain','',5.40,null,12.00,'Lager - North American Adjunct',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Abita Amber','Abita Brewing Company','US','Louisiana',5.00,null,12.00,'Amber Lager/Vienna ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Abita Purple Haze','Abita Brewing Company','US','Louisiana',4.00,null,12.00,'Fruit Beer ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Abita Turbodog','Abita Brewing Company','US','Louisiana',6.00,null,12.00,'Brown Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Anchor Liberty Ale','Anchor Brewing Company','US','California',5.90,null,12.00,'IPA - American',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Anchor Porter','Anchor Brewing Company','US','California',5.60,null,12.00,'Porter - American',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Anchor Steam','Anchor Brewing Company','US','California',5.00,null,12.00,'California Common ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Arkansas Red','Core Brewery','US','Arkansas',5.20,null,12.00,'Red Ale',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Atlas IPA','Marshall Brewing Company','US','Oklahoma',6.50,null,12.00,'IPA - American',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Bayou Teche Black Ale','Bayou Teche Brewing','US','Louisiana',5.25,null,12.00,'Schwarzbier ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Bayou Teche Smoked Wheat Ale','Bayou Teche Brewing','US','Louisiana',0.00,null,12.00,'Smoke Beer',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Blue Moon Belgian White Ale','Blue Moon Brewing Company','US','Colorado',5.40,null,12.00,'Witbier ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Bentonville Porter','Bentonville Brewing Co.','US','Arkansas',5.60,null,0.00,'Porter - Other',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Boulevard Single Wide IPA','Boulevard Brewing Co.','US','Missouri',5.70,null,24.00,'IPA - American',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Brotherhood Wheat','','US','',0.00,null,0.00,'',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Bud Light','Anheuser-Busch','US','Missouri',4.20,null,12.00,'Lager - American Light',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Budweiser','Anheuser-Busch','US','Missouri',5.00,null,12.00,'Lager - North American Adjunct',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Busch Can','Anheuser-Busch','US','Missouri',4.30,null,12.00,'Lager - North American Adjunct',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Coors Light','Coors Brewing Co.','US','Colorado',4.20,null,12.00,'Lager - American Light',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Crispin Original Cider','Crispin Cider Co.','US','California',5.00,null,12.00,'Cider ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Dale’s Pale Ale','Oskar Blues Brewery','US','Colorado',6.50,null,12.00,'Pale Ale - American',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Diamond Bear Irish Red','Diamond Bear Brewing Co.','US','Arkansas',4.60,null,12.00,'Irish Red Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Diamond Bear Pale Ale','Diamond Bear Brewing Co.','US','Arkansas',6.00,null,0.00,'English Pale Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Diamond Bear Paradise Porter','Diamond Bear Brewing Co.','US','Arkansas',4.95,null,12.00,'Porter - American',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Diamond Bear Presidential IPA','Diamond Bear Brewing Co.','US','Arkansas',6.00,null,16.00,'India Pale Ale (IPA) ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Diamond Bear Seasonal','Diamond Bear Brewing Co.','US','Arkansas',0.00,null,0.00,'(ask)',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Diamond Bear Southern Blonde','Diamond Bear Brewing Co.','US','Arkansas',4.14,null,12.00,'Pilsner - German',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Diamond Bear Two Term Double IPA','Diamond Bear Brewing Co.','US','Arkansas',10.00,null,12.00,'Imperial/Double IPA ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Dundee''s Honey Brown','Dundee Ales & Lagers','US','New York',4.50,null,12.00,'Lager - American Amber / Red',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('ESB','Core Brewery','US','Arkansas',6.00,null,12.00,'English Pale Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Founder''s All Day IPA (Can)','Founder’s Brewing Co.','US','Michigan',4.70,null,12.00,'IPA - Session',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Founder''s Centennial IPA','Founder’s Brewing Co.','US','Michigan',7.20,null,12.00,'IPA - American',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Founder’s Dirty Bastard','Founder’s Brewing Co.','US','Michigan',8.50,null,12.00,'Scottish Ale / Wee Heavy',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Half Wit Wheat','Charleville Brewing Co.','US','Missouri',4.50,null,12.00,'Witbier ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Hoptimistic IPA','Charleville Brewing Co.','US','Missouri',6.50,null,12.00,'IPA - American',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Lagunitas DayTime Fractional IPA','Lagunitas Brewing Company','US','California',4.65,null,12.00,'',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Lagunitas IPA','Lagunitas Brewing Company','US','California',6.20,null,12.00,'',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Lagunitas Pilsner','Lagunitas Brewing Company','US','California',6.00,null,12.00,'Pilsner - Czech ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Lazy Magnolia Jefferson Stout','Lazy Magnolia Brewing Company','US','Mississippi',4.65,null,12.00,'Stout - Milk / Sweet',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Lazy Magnolia Pecan Brown Ale','Lazy Magnolia Brewing Company','US','Mississippi',4.50,null,12.00,'Brown Ale - English',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Leghound Lager','Core Brewery','US','Arkansas',5.50,null,0.00,'Märzen',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('McNellie''s Pub Ale','Marshall Brewing Company','US','Oklahoma',5.00,null,12.00,'English Bitter',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Michelob ULTRA','Anheuser-Busch','US','Missouri',4.20,null,12.00,'Pale Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Miller Lite','Miller Brewing Co.','US','Wisconsin',4.17,null,12.00,'Lager - American Light',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Mother''s Three Blind Mice','Mother’s Brewing Co.','US','Missouri',5.50,null,12.00,'Brown Ale - American',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Mother’s Little Helper IPA','Mother’s Brewing Co.','US','Missouri',7.00,null,12.00,'IPA - American',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Moylan''s Danny''s Irish Red','Moylan’s Brewery','US','California',6.50,null,24.00,'Red Ale - Irish',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Moylan''s Old Blarney Barleywine','Moylan’s Brewery','US','California',10.00,null,24.00,'Barleywine - American',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Moylan''s White Christmas','Moylan’s Brewery','US','California',6.00,null,24.00,'Lager - Winter',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('New Belgium 1554 Black Lager','New Belgium Brewing Company','US','Colorado',5.60,null,12.00,'Lager - Black',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('New Belgium Abbey Ale','New Belgium Brewing Company','US','Colorado',7.00,null,12.00,'Belgian Dubbel',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('New Belgium Blue Paddle','New Belgium Brewing Company','US','Colorado',4.80,null,12.00,'Pilsner - Czech ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('New Belgium Fat Tire','New Belgium Brewing Company','US','Colorado',5.20,null,12.00,'Red Ale - American Amber / Red ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('New Belgium Ranger IPA','New Belgium Brewing Company','US','Colorado',6.50,null,12.00,'IPA - American',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('New Belgium Seasonal','New Belgium Brewing Company','US','Colorado',0.00,null,12.00,'(ask)',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('New Belgium Shift Pale Lager','New Belgium Brewing Company','US','Colorado',5.00,null,16.00,'Lager - Pale',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('New Belgium Sunshine Wheat','New Belgium Brewing Company','US','Colorado',4.80,null,12.00,'Pale Wheat Ale - American',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('New Belgium Trippel','New Belgium Brewing Company','US','Colorado',8.50,null,12.00,'Belgian Tripel ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Old Rasputin Russian Imperial Stout','North Coast Brewing Company','US','California',9.00,null,12.00,'Imperial Stout ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Pranqster','North Coast Brewing Company','US','California',7.60,null,12.00,'Blonde Ale - Belgian Blonde / Golden',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Scrimshaw','North Coast Brewing Company','US','California',4.70,null,12.00,'Pilsner ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Oatmeal Stout','Core Brewery','US','Arkansas',6.00,null,12.00,'Stout - Oatmeal',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Old Chub Scotch Ale','Oskar Blues Brewery','US','Colorado',8.00,null,12.00,'Scottish Ale / Wee Heavy',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Past Blue Ribbon','Pabst Brewing Company','US','Illinois',5.00,null,12.00,'Lager - North American Adjunct',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Pyramid Apricot Ale','Pyramid Breweries','US','Washington',5.10,null,12.00,'Fruit Beer ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Pyramid Hefeweizen','Pyramid Breweries','US','Washington',5.20,null,12.00,'Hefeweizen',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Redd’s Apple Ale','Redd’s Brewing Co.','US','Wisconsin',5.00,null,12.00,'Fruit Beer ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Rogue Chocolate Stout','Rogue Ales & Spirits','US','Oregon',5.80,null,22.00,'Stout - American',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Rogue Dead Guy','Rogue Ales & Spirits','US','Oregon',6.50,null,22.00,'Maibock/Helles Bock',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Rogue Hazelnut Brown Nectar','Rogue Ales & Spirits','US','Oregon',6.20,null,22.00,'Brown Ale - American',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Rogue Irish Style Lager','Rogue Ales & Spirits','US','Oregon',4.60,null,22.00,'Lager - Pale',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Rogue OREgasmic Ale','Rogue Ales & Spirits','US','Oregon',6.60,null,22.00,'Pale Ale - American',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Rogue Shakespeare Oatmeal Stout','Rogue Ales & Spirits','US','Oregon',5.70,null,22.00,'Stout - Oatmeal',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Rolling Rock','Latrobe Brewing Co.','US','Missouri',5.00,null,12.00,'Pale Lager',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Sam Adams Cherry Wheat','Boston Beer Company ','US','Massachussets',5.30,null,12.00,'Fruit Beer ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Sam Adams Light','Boston Beer Company ','US','Massachussets',4.30,null,12.00,'Lager - American Light',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Sam Adams Seasonal','Boston Beer Company ','US','Massachussets',0.00,null,12.00,'(ask)',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Samuel Adams Boston Lager','Boston Beer Company ','US','Massachussets',4.90,null,12.00,'Lager - Vienna / Amber',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Schlafly Dry Hopped APA','Schlafly - The Saint Louis Brewery','US','Missouri',7.20,null,12.00,'IPA - American',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Schlafly Kölsch','Schlafly - The Saint Louis Brewery','US','Missouri',4.80,null,12.00,'Kölsch',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Shiner Bock','Spoetzl Brewery','US','Texas',4.40,null,12.00,'Bock',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Shiner Premium','Spoetzl Brewery','US','Texas',4.50,null,12.00,'Lager - Pale',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Sierra Nevada Pale Ale','Sierra Nevada Brewing Co.','US','California',5.60,null,12.00,'Pale Ale - American',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Sierra Nevada Porter','Sierra Nevada Brewing Co.','US','California',5.60,null,12.00,'Porter - American',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Sierra Nevada Stout','Sierra Nevada Brewing Co.','US','California',5.80,null,12.00,'Stout - American',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Sierra Nevada Torpedo IPA','Sierra Nevada Brewing Co.','US','California',0.00,null,12.00,'',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Unfiltered Wheat Beer','Boulevard Brewing Co.','US','Misourri',4.00,null,16.00,'Wheat Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Waterfall Hoppy Wheat','Core Brewery','US','Arkansas',5.80,null,12.00,'Wheat/Pilsner',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Woodchuck Amber Cider','Woodchuck Cidery','US','Oregon',5.00,null,12.00,'Cider ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Woodchuck Granny Smith Cider','Woodchuck Cidery','US','Oregon',5.00,null,12.00,'Cider ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Woodchuck Pear Cider','Woodchuck Cidery','US','Oregon',4.00,null,12.00,'Cider ',false,false);


INSERT INTO USER (name,email,password,nickname,role,lists_completed) VALUES ('James Thomas','james@just-james.com','admin','Jimmy','ADMIN',0);