INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Beer','Brewery','Country','Region',0.00,null,0.00,'Style',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Saddlebock Dunkelweiz','','US','Arkansas',7.00,null,16.00,'',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Boulevard Unfiltered Wheat','','US','Misourri',4.00,null,16.00,'Wheat Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Diamond Bear Pale Ale','','US','Arkansas',6.00,null,16.00,'English Pale Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Diamond Bear Presidential IPA','','US','Arkansas',6.00,null,16.00,'India Pale Ale (IPA) ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Saddlebock Dirty Blonde Ale','','US','Arkansas',5.00,null,16.00,'',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Abita Amber','','US','Louisiana',5.00,null,12.00,'Amber Lager/Vienna ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Abita Purple Haze','','US','Louisiana',4.00,null,12.00,'Fruit Beer ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Abita Turbodog','','US','Louisiana',6.00,null,12.00,'Brown Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Affligem Triple','Affligem Brouwerij','Netherlands','',9.00,null,25.00,'Tripel ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Amstel Light','','Netherlands','',4.00,null,12.00,'Pale Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Anchor Liberty Ale','','US','California',6.00,null,12.00,'American Pale Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Anchor Porter','','US','California',6.00,null,12.00,'Porter ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Anchor Steam','','US','California',5.00,null,12.00,'California Common ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Avery Hog Heaven Barley Wine','','US','Colorado',9.00,null,22.00,'Barley Wine ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Avery Mephistopheles Stout','','US','Colorado',17.10,null,12.00,'Imperial Stout ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Avery Samael''s Oak Aged','','US','Colorado',15.00,null,12.00,'Barley Wine ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Avery The Beast Grand Cru','','US','Colorado',16.00,null,12.00,'Belgian Strong Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Avery The Czar Imperial Stout','','US','Colorado',9.00,null,22.00,'Imperial Stout ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Avery The Kaiser Imperial Oktoberfest','','US','Colorado',10.00,null,22.00,'Oktoberfest/Marzen ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Avery The Maharaja','','US','Colorado',10.00,null,22.00,'Imperial/Double IPA ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Ayinger Celebrator Doppelbock','','Germany','',7.00,null,12.00,'Doppelbock ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Bass Ale','','Belgium','',5.00,null,12.00,'English Pale Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Becks','','Germany','',5.00,null,12.00,'Premium Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Belhaven Scottish Ale','','Scotland','',5.00,null,12.00,'Scottish Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Bitburger Pilsner','','Germany','',5.00,null,12.00,'Pilsner ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Monty Python''s Holy Grail Ale','Black Sheep Brewery','England','',4.70,null,12.00,'English Pale Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Blue Moon Belgian Style Wheat','','US','Colorado',5.00,null,12.00,'Witbier ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Blue Moon Grand Cru','','US','Illinois',9.00,null,22.00,'Witbier ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Boulevard Double Wide IPA','','US','Missouri',9.00,null,24.00,'Imperial/Double IPA ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Bud Light','Anheuser-Busch','Belgium','',4.20,null,12.00,'Pale Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Budweiser','Anheuser-Busch','Belgium','',5.00,null,12.00,'Pale Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Carta Blanca','','Mexico','',4.00,null,12.00,'Pale Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Cerveza Tecate','','Mexico','',5.00,null,12.00,'Pale Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Chimay Cinq Cents (White)','Bieres de Chimay','Belgium','',8.00,null,11.00,'Tripel ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Chimay Grand Reserve','Bieres de Chimay','Belgium','',9.00,null,11.00,'Belgian Strong Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Chimay Premiere (Red)','Bieres de Chimay','Belgium','',7.00,null,11.00,'Dubbel ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Coors Light','','US','Colorado',4.00,null,12.00,'Pale Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Arkansas Red','Core Brewery','US','Arkansas',5.20,null,12.00,'Red Ale',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Barney''s Imperial Red','Core Brewery','US','Arkansas',10.00,null,22.00,'India Pale Ale (IPA) ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Behemoth Pilsner','Core Brewery','US','Arkansas',5.00,null,12.00,'Bohemian-Style Pilsner',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Brae Scotch Heavy','Core Brewery','US','Arkansas',10.00,null,22.00,'Scottish Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Easy Livin'' IPA','Core Brewery','US','Arkansas',5.00,null,12.00,'India Pale Ale (IPA) ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('ESB','Core Brewery','US','Arkansas',6.00,null,12.00,'English Pale Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Hazelnut Southern Brown','Core Brewery','US','Arkansas',6.00,null,12.00,'Brown Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Hilltop IPA','Core Brewery','US','Arkansas',6.00,null,12.00,'India Pale Ale (IPA) ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Imperial Chocolate','Core Brewery','US','Arkansas',10.00,null,22.00,'Stout ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Leghound Lager','Core Brewery','US','Arkansas',6.00,null,12.00,'Oktoberfest',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Oatmeal Stout','Core Brewery','US','Arkansas',6.00,null,12.00,'Stout ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Ol'' Grumpy Barley Wine','Core Brewery','US','Arkansas',10.00,null,22.00,'Barley Wine ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Pumpkin Pie','Core Brewery','US','Arkansas',6.00,null,12.00,'',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Raspberry Lager','Core Brewery','US','Arkansas',4.00,null,12.00,'Lager',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Toasted Coconut','Core Brewery','US','Arkansas',6.00,null,12.00,'Southern Brown Ale',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Waterfall Hoppy Wheat','Core Brewery','US','Arkansas',6.00,null,12.00,'Wheat/Pilsner',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Corona','','Mexico','',5.00,null,12.00,'Pale Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Corona Light','','Mexico','',4.00,null,12.00,'Pale Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Diamond Bear Irish Red','','US','Arkansas',6.00,null,12.00,'Irish Red Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Diamond Bear Paradise Porter','','US','Arkansas',6.00,null,12.00,'Porter ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Diamond Bear Southern Blonde','','US','Arkansas',4.00,null,12.00,'Pale Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Diamond Bear Two Term Double IPA','','US','Arkansas',10.00,null,12.00,'Imperial/Double IPA ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Dos Equis XX Amber','','US','Missouri',5.00,null,12.00,'Amber Lager/Vienna ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Dos Equis XX Special Lager','','US','Missouri',4.00,null,12.00,'Pale Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Dundee''s Honey Brown','','US','New York',5.00,null,12.00,'Premium Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Estrella Damm','','Spain','',5.00,null,12.00,'Pale Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Grolsch','','England','',5.00,null,14.00,'Premium Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Guinness','','Ireland','',4.00,null,12.00,'Dry Stout ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Harp Lager','','England','',5.00,null,12.00,'Pale Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Heineken','','Netherlands','',5.00,null,12.00,'Pilsner ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Heineken Light','','Netherlands','',3.00,null,12.00,'Pilsner ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Hoegaarden White','Brouwerij van Hoegaarden','Belgium','',5.00,null,12.00,'Witbier ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Kirin','','Japan','',5.00,null,12.00,'American Pale Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Konig Ludwig Weiss','','Germany','',6.00,null,12.00,'German Hefeweizen ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Kostritzer Schwarzbier','','Germany','',5.00,null,14.00,'Schwarzbier ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Labatt Blue','','Canada','',5.00,null,12.00,'Pilsner ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Lindeman''s Framboise','','Belgium','',3.00,null,12.00,'Lambic - Fruit ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Lindemans Peche Lambic','','Belgium','',3.00,null,12.00,'Lambic - Fruit ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Michelob Ultra','','Belgium','',4.00,null,12.00,'Pale Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Miller Lite','','US','Wisconsin',4.00,null,12.00,'Pale Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Modelo Especial','','Mexico','',4.00,null,12.00,'Pale Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Moosehead Lager','','Canada','',5.00,null,12.00,'Pale Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Moretti','Birra Moretti','Italy','',5.00,null,12.00,'Pale Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Moretti La Rossa','Birra Moretti','Italy','',7.20,null,12.00,'Doppelbock ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Moylan''s Danny''s Irish Red','','US','California',7.00,null,24.00,'Red Ale - Irish',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Moylan''s Old Blarney Barleywine','','US','California',10.00,null,24.00,'Barleywine',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Moylan''s White Christmas','','US','California',6.00,null,24.00,'Lager - Winter',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Mythos','','Greece','',5.00,null,12.00,'Pale Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Negra Modelo','','Mexico','',5.00,null,12.00,'Amber Lager/Vienna ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('New Belgium 1554 Black Lager','','US','Colorado',6.00,null,12.00,'Schwarzbier ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('New Belgium Abbey Ale','','US','Colorado',7.00,null,12.00,'Dubbel ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('New Belgium Belgo IPA','','US','Colorado',7.00,null,12.00,'India Pale Ale (IPA) ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('New Belgium Blue Paddle','','US','Colorado',5.00,null,12.00,'Pilsner ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('New Belgium Fat Tire','','US','Colorado',5.00,null,12.00,'Amber Ale / Red Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('New Belgium Ranger IPA','','US','Colorado',7.00,null,12.00,'India Pale Ale (IPA) ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('New Belgium Sunshine Wheat','','US','Colorado',5.00,null,12.00,'Wheat Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('New Belgium Trippel','','US','Colorado',8.00,null,12.00,'Tripel ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Newcastle Brown Ale','Tadcaster Brewery','England','',4.70,null,12.00,'Brown Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('North Coast Old Rasputin Russian Imperial Stout','','US','California',9.00,null,12.00,'Imperial Stout ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('North Coast PranQster','','US','California',8.00,null,12.00,'Belgian Strong Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('North Coast Scrimshaw','','US','California',5.00,null,12.00,'Pilsner ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Orval Trappist','','Belgium','',6.00,null,12.00,'Belgian Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Pacifico Clara','','Mexico','',5.00,null,12.00,'Pale Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Peroni','','England','',5.00,null,12.00,'Pale Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Pilsner Urquell','','Czech Republic','',4.00,null,12.00,'Czech Pilsner ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Pyramid Apricot Ale','','US','Washington',5.00,null,12.00,'Fruit Beer ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Pyramid Hefeweizen','','US','Washington',5.00,null,12.00,'Wheat Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Redd’s Apple Ale','','US','Wisconsin',5.00,null,12.00,'Fruit Beer ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Red Stripe','','Jamaica','',5.00,null,12.00,'Pale Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Rogue Chocolate Stout','','US','Oregon',6.00,null,22.00,'Sweet Stout ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Rogue Dead Guy','','US','Oregon',7.00,null,22.00,'Maibock ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Rogue Hazelnut Brown Nectar','','US','Oregon',6.00,null,22.00,'Brown Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Rogue Kells','','US','Oregon',5.00,null,22.00,'',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Rogue Shakespeare Stout','','US','Oregon',6.00,null,22.00,'Stout ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Rolling Rock','','Belgium','',5.00,null,12.00,'Pale Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Sam Adams Cherry Wheat','','US','Massachussets',5.00,null,12.00,'Wheat Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Sam Adams Light','','US','Massachussets',4.00,null,12.00,'Premium Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Sam Adams Seasonal','','US','Massachussets',6.00,null,12.00,'Premium Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Sam Smith Nut Brown','','England','',5.00,null,12.00,'Brown Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Samuel Adams Boston Lager','','US','Massachussets',5.00,null,12.00,'Amber Lager/Vienna ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Samuel Smith Oatmeal Stout','','England','',5.00,null,16.00,'Sweet Stout ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Samuel Smith Pale Ale','','England','',5.00,null,12.00,'American Pale Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Samuel Smith Pure Brewed Lager','','England','',5.00,null,12.00,'Premium Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Samuel Smith''s Imperial Stout','','England','',7.00,null,12.00,'Imperial Stout ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Samuel Smith''s Winter Welcome Ale','','England','',6.00,null,12.00,'Winter Warmer ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Samuel Smith Taddy Porter','','England','',5.00,null,12.00,'Porter ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Sapporo','','Japan','',5.00,null,12.00,'Pale Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Shiner Blonde','','US','Texas',4.00,null,12.00,'Premium Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Shiner Bock','','US','Texas',4.00,null,12.00,'Amber Lager/Vienna ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Sierra Nevada Pale Ale','','US','California',6.00,null,12.00,'American Pale Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Sierra Nevada Porter','','US','California',6.00,null,12.00,'Porter ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Sierra Nevada Stout','','US','California',6.00,null,12.00,'Stout ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Spaten Franziskaner Hefe-Weiss','','Germany','',5.00,null,16.00,'German Hefeweizen ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Spaten Optimator','','Germany','',8.00,null,14.00,'Doppelbock ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Spaten Premium Lager','','Germany','',5.00,null,12.00,'Premium Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Stella Artois','','Belgium','',5.00,null,12.00,'Pale Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('St. Pauli Girl','','Germany','',5.00,null,12.00,'Premium Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('St. Pauli Girl Dark','','Germany','',5.00,null,12.00,'Dunkel ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Sudwerk Hefeweizen Bavarian Wheat','','US','California',5.00,null,12.00,'Hefeweizen',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Sudwerk Lager','','US','California',5.00,null,12.00,'Lager',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Sudwerk Marzen','','US','California',5.00,null,12.00,'Marzen',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Sudwerk Pilsner','','US','California',5.00,null,12.00,'Pilsner ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Taj Mahal','','India','',5.00,null,14.00,'Pale Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Tsingtao','','Japan','',5.00,null,12.00,'Premium Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Wells & Young''s Double Chocolate Stout','','England','',5.00,null,14.00,'Stout ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Xingu','','Brazil','',4.00,null,12.00,'Schwarzbier ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Boddington’s Pub Ale','Boddington’s Brewery','England','',5.00,null,12.00,'Brown Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Busch','','US','',5.00,null,12.00,'Premium Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Foster''s Lager','Foster’s Group','Australia','',5.00,null,27.00,'Pale Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Fuller''s London Pride','','England','',5.00,null,11.00,'English Pale Ale ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('New Belgium Shift Pale Lager','','US','Colorado',5.00,null,16.00,'Pale Lager ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Blue Mountain Woodchuck Amber Cider','','US','Oregon',5.00,null,12.00,'Cider ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Crispin Original Cider','','US','Minnesota',5.00,null,12.00,'Cider ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Woodchuck Granny Smith Cider','','US','Oregon',5.00,null,12.00,'Cider ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Woodchuck Pear Cider','','US','Oregon',5.00,null,12.00,'Cider ',false,false);
INSERT INTO BEER (name,brewery,country,region,abv,ibu,oz,style,discontinued,oos) VALUES ('Past Blue Ribbon','Pabst Brewing Company','US','',5.00,null,12.00,'Lager',false,false);


INSERT INTO USER (name,email,password,nickname,role,lists_completed) VALUES ('James Thomas','james@just-james.com','admin','Jimmy','ADMIN',0);